// DO NOT EDIT THIS FILE MANUALLY.
// Regenerate after any schema change:
//   supabase gen types typescript --local > src/types/database.types.ts

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          created_at?: string;
        };
        Update: {
          full_name?: string | null;
        };
      };
      api_keys: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          key_hash: string;
          key_prefix: string;
          is_active: boolean;
          created_at: string;
          last_used_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          key_hash: string;
          key_prefix: string;
          is_active?: boolean;
          created_at?: string;
          last_used_at?: string | null;
        };
        Update: {
          is_active?: boolean;
          last_used_at?: string | null;
        };
      };
      usage_logs: {
        Row: {
          id: string;
          api_key_id: string;
          user_id: string;
          email_domain: string;
          result: 'valid' | 'invalid';
          format_check: boolean;
          mx_check: boolean;
          duration_ms: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          api_key_id: string;
          user_id: string;
          email_domain: string;
          result: 'valid' | 'invalid';
          format_check: boolean;
          mx_check: boolean;
          duration_ms: number;
          created_at?: string;
        };
        Update: Record<string, never>;
      };
    };
  };
};
